### ISSUE TITLE
DNS cache in `aiohttp.TCPConnector` causes client requests to timeout when host address changes

### ISSUE THREAD

**Issue by hanula** [elastic/elasticsearch-py-async#11]
Hi!

Using domain-based elasticsearch hosts that change their IP over time can cause `AsyncElasticsearch` client to timeout requests as the default DNS cache resolves the hostname with old address.
 
For example, with Elasticsearch Heroku Add-ons that run on AWS, the host URL doesn't change and looks like `https://abcdef-123455.eu-west-1.bonsaisearch.net`, but the IP address can change over time. Because of the DNS cache - which isn't flushed - the client tries to send requests to wrong host IP and failes.

Solution might be to pass explicit `use_dns_cache` param to `aiohttp.TCPConnector` [in the constructor of `AIOHttpConnection`](https://github.com/elastic/elasticsearch-py-async/blob/c76817dd24e4cfa0ced0fa13fa4a70721d649df0/elasticsearch_async/connection.py#L29). 
Additionally, because of the default DNS resolver being [thread-based](https://github.com/KeepSafe/aiohttp/blob/9fbb7d708375e0ba01d435c1e8cf41912381c0fc/aiohttp/resolver.py#L17), a `dns_resolver` param could be used to specify own, for example `aiodns`-based [AsyncResolver](https://github.com/KeepSafe/aiohttp/blob/9fbb7d708375e0ba01d435c1e8cf41912381c0fc/aiohttp/resolver.py#L47), although it was removed as default one because of compatibility [issues with IPv6 systems](https://github.com/KeepSafe/aiohttp/issues/559).

I can submit a PR with this solution soon.
What do you think?

**Comment by HonzaKral** [comment]
Hi,

thank you very much for the report. The default that we choose should be the safest option that works everywhere (turning off DNS cache in this case).

We can then provide additional options to improve performance/experience in some circumstances, but that is not the highest priority, especially if this can be implemented as a "plugin" - a custom subclass of the `Connection` class we are using.

A PR would be most welcome!

Thank you,
Honza

**Comment by HonzaKral** [comment]
Released as `5.1.0`
