### ISSUE TITLE
Elasticsearch 2.x support?

### ISSUE THREAD

**Issue by hanula** [elastic/elasticsearch-py-async#13]
`master` branch only supports Elasticsearch>=5.0.0, but some people still need to use `2.x` and want to use `elasticsearch-py-async` with it. 
Can we have a separate enhancements and bugfixes branch for `2.x` like `elasticsearch-py` does?

I've created [2.x branch](https://github.com/hanula/elasticsearch-py-async/tree/2.x) to which I'd like to backport #12.

What do you think? If possible, how to proceed with it?
Thanks

**Comment by HonzaKral** [comment]
`2.x` branch would be great, we could do bugfix releases off of it just like we do for `elasticsearch-py`. I have created the branch in this repo so you can push PRs against it.

Once I have time to review your PR I will do both `5.x` and `2.x` releases.

Thanks for bringing this up!

**Comment by hanula** [comment]
Great! 
Thank you.

How do you work with fixes in multiple versions of `elasticsearch-py`? Fix it in lowest affected version and merge it to others? In other words, are higher versions always mergable with previous ones?

**Comment by HonzaKral** [comment]
I typically only backport serious bug fixes to the `2.x` branch but development always occurs in `master`. We don't have any strict policy around merging and mergability since the traffic isn't that big.

**Comment by hanula** [comment]
Ok.
