### ISSUE TITLE
Problems with CA_CERTS

### ISSUE THREAD

**Issue by quasiben** [elastic/elasticsearch-py-async#17]
I need to user certs with my ES connection.  In the code it appears as though `ca_certs` is accepted in the constructor but goes unused.  Is that correct?  Is this a bug or am I not correctly using ca_certs?

**Comment by quasiben** [comment]
I think the solution here is to support an `ssl_context` in the [TCPConnector](https://github.com/elastic/elasticsearch-py-async/blob/master/elasticsearch_async/connection.py#L29-L33).  I'd suggest doing this by adding ssl_context as a top level parameter in the constructor for `AIOHttpConnection`

**Comment by fxdgear** [comment]
@quasiben Thanks for the feedback. `ca_certs` is being deprecated. But hasn't been removed yet. 

Though I missed adding the ability to use `ssl_context` to the TCPConnector. 

Thanks for the feedback will get on this.

**Comment by fxdgear** [comment]
This has been fixed in https://github.com/elastic/elasticsearch-py-async/pull/30
