### ISSUE TITLE
Package status

### ISSUE THREAD

**Issue by tomas-fp** [elastic/elasticsearch-py-async#3]
Is there any plan to improve or merge this package into the standard Python package?

**Comment by HonzaKral** [comment]
This package is now available on PyPI as elasticsearch-async - https://pypi.python.org/pypi/elasticsearch-async

Thanks for this report, it looks like I have forgotten to update the README to reflect this situation!

**Comment by tomas-fp** [comment]
Is this supposed to work?:
```python
await async_client.indices.create(index=my_index, body=body)
```

**Comment by HonzaKral** [comment]
Yes, that is indeed supposed to work, are you running into any issues? If so please open a separate issue.

I updated the README to reflect the release status.
