### ISSUE TITLE
Compatible with elasticsearch-dsl

### ISSUE THREAD

**Issue by digitaldavenyc** [elastic/elasticsearch-py-async#31]
Is it possible to use this with [elasticsearch-dsl](https://github.com/elastic/elasticsearch-dsl-py)?

**Comment by 3lnc** [comment]
Not as drop-in replacements.

Dsl does a lot of sync calls, i.e. `DocType.save()` or `Search.execute()`. You need to subclass and change it to `await` calls from underlying async transport.

**Comment by udfalkso** [comment]
The DSL Search has a to_dict() method that you can then pass as the body to the async es client.  Seems to work for me.  

Something like this:
```
q = # build your query
s = Search(index=INDEX_NAME).query(q)
r = await self.elastic_search_client.search(index=INDEX_NAME, body=s.to_dict())
```

**Comment by sethmlarson** [comment]
This issue is being tracked on the Elasticsearch-DSL repository here: https://github.com/elastic/elasticsearch-dsl-py/issues/1355
Closing in favor of that issue.
