### ISSUE TITLE
Release a ES6.0 compatible version

### ISSUE THREAD

**Issue by nsbk** [elastic/elasticsearch-py-async#32]
Hi there,

We are moving to ES6.0 and would very much like to keep using `elasticsearch-py-async`. Since support for the new ES version is there thanks to https://github.com/elastic/elasticsearch-py-async/pull/29, do you think it would be possible to release a new version that includes this changes?

Thanks a lot!

**Comment by 3lnc** [comment]
@HonzaKral is there anything that need to be fixed prior to PyPI release?

**Comment by nheng0** [comment]
Hello,

Could you please provide us with a release date for an ES6.0-compatible version of your product?

Thanks a lot for your help.

**Comment by Hattivat** [comment]
The github version is working fine, so I use it by copying it raw into my docker container. Could you please make an official release so I can ran it via normal pip install like a civilized person?

**Comment by hh-h** [comment]
New release would be great!

**Comment by fxdgear** [comment]
release pushed!
