### ISSUE TITLE
Twisted Backend

### ISSUE THREAD

**Issue by jomido** [elastic/elasticsearch-py-async#4]
Thank you for your work on this async adapter. Really great.

I would like to implement a Twisted backend. This is prompted by [issue 458 from the elasticsearch-py](https://github.com/elastic/elasticsearch-py/issues/458) repository.

Should I submit a PR against this repository, or would a separate repository be better (i.e. `elasticsearch-py-twisted`)? If the former, then I would create two new directories `elasticsearch-async/twisted` and `test_elasticsearch_async/twisted`. (Some code duplication might crop up, but a subsequent PR could take care of refactoring.)

**Comment by HonzaKral** [comment]
A PR to this repository would be great! We can then abstract away the common stuff needed for the two backends and have optional dependencies on asyncio/twisted.

Let me know if there is anything I can do to help!

**Comment by eranhirs** [comment]
For an existing twisted backend you might want to use
https://github.com/avihad/twistes

**Comment by sethmlarson** [comment]
If this functionality still desirable you should open an issue on the [`elasticsearch`](https://github.com/elastic/elasticsearch-py) repository.
