### ISSUE TITLE
latest aiohttp support for 5.x branch

### ISSUE THREAD

**Issue by amatai** [elastic/elasticsearch-py-async#46]
Issue #37 was fixed for elasticsearch-py-async versions 6.x and above.
Version 6.0.0 depends on elasticsearch 6.0.0, with has compatability with ElasticSearch 6.x

In real world, Elasticsearch 5.x is widely installed, which means elasticsearch-py-async 5.x is needed to talk to ES 5.x cluster.

Using 5.x causes the same issue as #37 with latest aiohttp.

Is there a way to get the `Timeout` to `async_timeout` change implemented for 5.x branch?
In essence, similar to how https://github.com/elastic/elasticsearch-py package is available for different version of ElasticSearch, similarly, the async version of the client should be available. 

I am willing to contribute.

**Comment by sethmlarson** [comment]
The 5.x branch is no longer supported so I'm closing this issue.
