### ISSUE TITLE
[Feature request] AsyncElasticsearch should implement an async context manager

### ISSUE THREAD

**Issue by albins** [elastic/elasticsearch-py-async#48]
It would be nice if `AsyncElasticsearch` implemented the magic methods (specifically `__aenter__()` and `__aexit__()`) to become an async context manager, which would allow code like this:
```python
async with AsyncElasticsearch() as client:
    print(await client.info()) 
```
and have the session closed.

Happy to implement this[ similar to how aiohttp has done it](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L820) if you are interested!

**Comment by fxdgear** [comment]
@albins If you write it I'll review it! :) 

Thanks

**Comment by albins** [comment]
@fxdgear Great; I'll start working on it then!
