### ISSUE TITLE
Can't access ElasticSearch in docker container by domain name

### ISSUE THREAD

**Issue by lly123** [elastic/elasticsearch-py-async#53]
Hi guys,

I found in docker container your lib can't access es by domain name directly, so I have to convert domain to ip address by "socket.gethostbyname".

This issue maybe relates to https://stackoverflow.com/questions/40347726/python-3-5-asyncio-and-aiohttp-errno-101-network-is-unreachable

Please check

**Comment by sethmlarson** [comment]
I don't think this issue is due to this library. Closing this for now.
