### ISSUE TITLE
How can I use proxy to connect to elasticsearch ?

### ISSUE THREAD

**Issue by RatanShreshtha** [elastic/elasticsearch-py-async#58]
I am trying to connect elasticsearch cluster when I am behind a corporate proxy maybe something like 

```
from elasticsearch import Elasticsearch, RequestsHttpConnection


class MyConnection(RequestsHttpConnection):
    def __init__(self, *args, **kwargs):
        proxies = kwargs.pop("proxies", {})
        super(MyConnection, self).__init__(*args, **kwargs)
        self.session.proxies = proxies


es = Elasticsearch(
    ["https://url_to_elasticsearch"],
    connection_class=MyConnection,
    proxies=proxies,
    use_ssl=True,
    http_auth=("username", "password"),
)
```

**Comment by fxdgear** [comment]
@RatanShreshtha thanks for the issue. 

Unfortuantly using `urllib3` we don't support proxies yet, so as a work around you can use the `requests` library, similar to what you're suggesting. 

for more reference please see:

* https://github.com/elastic/elasticsearch-py/issues/860
* https://github.com/elastic/elasticsearch-py/issues/357
* https://github.com/elastic/elasticsearch-py/issues/275#issuecomment-143682556

**Comment by RatanShreshtha** [comment]
I am not sure how can I use the above code snippet for **elasticsearch-py-async** as here the aiohttp lib is used.

**Comment by sethmlarson** [comment]
Since we won't be adding new features to this library I'll be closing this. See https://github.com/elastic/elasticsearch-py-async/issues/81 for more information. You can use a transparent HTTP proxy (as opposed to forwarding/tunnel) which should work fine with any client.

**Comment by qbit-git** [comment]
AsyncElasticsearch cannot recognize http_proxy
Windows 10
ES 7.10
