### ISSUE TITLE
Connect elasticsearch with ipv6 address

### ISSUE THREAD

**Issue by YvanZ** [elastic/elasticsearch-py-async#64]
When I connect my elsaticsearch with an ipv6 address like this:

```python
ES_CLIENT = AsyncElasticsearch(
    hosts=['http://[2002:ac1f:91c8::127.0.0.1]:9200'],
    timeout=120,
    sniff_on_start=True,
    retry_on_timeout=True,
    max_retries=5,
    loop=self.loop
)
```

The connection will be failed because of the address will be converted to `2002:ac1f:91c8::127.0.0.1`, and aiohttp can't establish the connection with that kind of address.

With this situation, I have prepared a pull request if you think this is a bug, or how can I connect my elasticsearch with IP address like that.

**Comment by sethmlarson** [comment]
If aiohttp doesn't support connecting to these addresses then this issue should be raised in that project. We can't do much to work around this.
