### ISSUE TITLE
Asyncio.run Not Supported 

### ISSUE THREAD

**Issue by mathfish** [elastic/elasticsearch-py-async#65]
I tried to use the Python 3.7 approach for asyncio via asyncio.run() and not loop.run_until_complete(). This produces the following error: 

`RuntimeError: Task <Task pending coro=<query_elasticsearch() running at <ipython-input-10-b627b3d0f9d9>:23> cb=[as_completed.<locals>._on_completion() at /miniconda3.7/lib/python3.7/asyncio/tasks.py:520]> got Future <Task pending coro=<AsyncTransport.main_loop() running at /lib/python3.7/site-packages/elasticsearch_async/transport.py:143>> attached to a different loop`

If this is not a bug but just not supported yet, is there plans to include this? Thanks!

**Comment by AlexHagerman** [comment]
Is this running in a Jupyter Notebook?

Can you post a snippet for replicating the `RuntimeError`?

**Comment by mathfish** [comment]
Yes it is running in a notebook/jupyter lab:
`
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>

~/miniconda3.7/lib/python3.7/asyncio/runners.py in run(main, debug)
     41         events.set_event_loop(loop)
     42         loop.set_debug(debug)
---> 43         return loop.run_until_complete(main)
     44     finally:
     45         try:

~/miniconda3.7/lib/python3.7/asyncio/base_events.py in run_until_complete(self, future)
    582             raise RuntimeError('Event loop stopped before Future completed.')
    583 
--> 584         return future.result()
    585 
    586     def stop(self):

<ipython-input-8-1c0e53b79776> in main(num_reqs, loop)
     31     ea_requests = []
     32     for future in asyncio.as_completed(futures):
---> 33         requests = await future
     34         ea_requests.extend([loop.run_in_executor(proc_executor, _clean_and_build_ea_request, request) for request in requests])
     35 

~/miniconda3.7/lib/python3.7/asyncio/tasks.py in _wait_for_one()
    531             # Dummy value from _on_timeout().
    532             raise futures.TimeoutError
--> 533         return f.result()  # May raise f.exception().
    534 
    535     for f in todo:

<ipython-input-8-1c0e53b79776> in query_elasticsearch(num_req)
     22     index_date = datetime.utcnow().date().strftime("%Y.%m.%d")
     23     query = get_query(num_req)
---> 24     query_results = await elastic_src_async_eu_client.search(index=f'my-index-{prod_or_stage}_{index_date}', body=json.dumps(query))
     25     return [hit['_source'] for hit in query_results['hits']['hits']]
     26 

RuntimeError: Task <Task pending coro=<query_elasticsearch() running at <ipython-input-8-1c0e53b79776>:24> cb=[as_completed.<locals>._on_completion() at /Users/<removed>/miniconda3.7/lib/python3.7/asyncio/tasks.py:520]> got Future <Task pending coro=<AsyncTransport.main_loop() running at /Users/<removed>/Projects/Python/<removed>/envs/<removed>/lib/python3.7/site-packages/elasticsearch_async/transport.py:143>> attached to a different loop
`

**Comment by mathfish** [comment]
I also tried creating the event loop and passing it the AsyncElasticsearch constructor and got the same RuntimeError. As per-the-usual, totally could be user error

**Comment by AlexHagerman** [comment]
Thanks, I now I ran into some `asyncio` issues in notebooks a while back since it has it's own event loop in the background. Can you verify if this works in a repl?

You may be running into this https://github.com/jupyter/notebook/issues/4312

**Comment by mathfish** [comment]
Hhhmm. I'll check. It does work in a notebook when I use a loop.run_until_complete() approach, so asycnio does work in general in a notebook, though I had to downgrade Tornado.

**Comment by AlexHagerman** [comment]
I'll try to replicate, if you can give me a snippet that will help me attempt to replicate this. One thing of note is that 

`run_until_complete` is an event loop method https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_until_complete which is why it will work in a notebook.

`run` is a function https://docs.python.org/3/library/asyncio-task.html#asyncio.run

And the doc mentions

```
This function cannot be called when another asyncio event loop is running
in the same thread.
```

Because

```
This function always creates a new event loop and closes it at the end. 
It should be used as a main entry point for asyncio programs, 
and should ideally only be called once.
```

**Comment by mathfish** [comment]
Ok here is a snippet. I put the below in a .py file and ran it from the command line and got the same error output. I am using Python 3.7. 

```
from elasticsearch_async import AsyncElasticsearch
import asyncio

async_search_client = AsyncElasticsearch(hosts=HOST,
                                         port=PORT,
                                         scheme="http",
                                         timeout=90,
                                         max_retries=5,
                                         retry_on_timeout=True)

async def print_info():
    info = await async_search_client.info()
    print(info)
# Python 3.7 way to run asyncio
asyncio.run(print_info())

# Original way below
#loop = asyncio.get_event_loop()
#loop.run_until_complete(print_info())
#loop.run_until_complete(async_search_client.transport.close())
#loop.close()
```

**Comment by AlexHagerman** [comment]
Thank you for the information @mathfish 

This morning I was able to replicate the error while setting the `PYTHONASYNCIODEBUG` environment variable.

Looks like this happens based on how we are handling the event loop and transport to communicate with the endpoint. 

```
RuntimeError: 
Task <Task pending coro=<print_info() running at async_debug.py:13> 
cb=[_run_until_complete_cb() at /usr/local/lib/python3.7/asyncio/base_events.py:158]> got 
Future <Task pending coro=<AsyncTransport.main_loop() running at /Users/alexander/.virtualenvs/elasticasync/lib/python3.7/site-packages/elasticsearch_async/transport.py:143> 
created at /Users/alexander/.virtualenvs/elasticasync/lib/python3.7/site-packages/elasticsearch_async/transport.py:218> attached to a different loop
Task was destroyed but it is pending!

task: <Task pending coro=<AsyncTransport.main_loop() running at /Users/alexander/.virtualenvs/elasticasync/lib/python3.7/site-packages/elasticsearch_async/transport.py:143> 
created at /Users/alexander/.virtualenvs/elasticasync/lib/python3.7/site-packages/elasticsearch_async/transport.py:218>
<CoroWrapper AsyncTransport.main_loop() running at /Users/alexander/.virtualenvs/elasticasync/lib/python3.7/site-packages/elasticsearch_async/transport.py:143, created at /Users/alexander/.virtualenvs/elasticasync/lib/python3.7/site-packages/elasticsearch_async/transport.py:217> was never yielded from

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x110728668>
```

We will have to look into what steps we need to take in `transport` and `connection` to handle the event loop in a way that is compatible with `asyncio.run()`.

**Comment by erlendvollset** [comment]
Any updates on this?

**Comment by danielzgtg** [comment]
A workaround would be to create the `AsyncElasticsearch` instance inside the loop. That will make sure it finds the right loop.

For the above snippet, modifying it to look like this makes it work:

```python
from elasticsearch_async import AsyncElasticsearch
import asyncio

# async_search_client removed from this line

async def print_info():
    # async_search_client added on following line:
    async_search_client = AsyncElasticsearch(hosts=HOST,
                                             port=PORT,
                                             scheme="http",
                                             timeout=90,
                                             max_retries=5,
                                             retry_on_timeout=True)
    info = await async_search_client.info()
    print(info)
# Python 3.7 way to run asyncio
asyncio.run(print_info())
```

Additionally, now that Python 3.8 is out, things work even better:

```
$ python3.8 -m asyncio
asyncio REPL 3.8.2 (default, Feb 25 2020, 13:04:52) 
[GCC 9.2.1 20200224] on linux
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> from elasticsearch_async import AsyncElasticsearch
>>> es = AsyncElasticsearch("127.0.0.1:9200")
>>> async def print_info():
...  info = await es.info()
...  print(info)
... 
>>> await print_info()
{'name': '3b3393e4f747', 'cluster_name': 'docker-cluster', 'cluster_uuid': 'sf77lxN4QXGnBJ03bGQKEA', 'version': {'number': '7.6.0', 'build_flavor': 'default', 'build_type': 'docker', 'build_hash': '7f634e9f44834fbc12724506cc1da681b0c3b1e3', 'build_date': '2020-02-06T00:09:00.449973Z', 'build_snapshot': False, 'lucene_version': '8.4.0', 'minimum_wire_compatibility_version': '6.8.0', 'minimum_index_compatibility_version': '6.0.0-beta1'}, 'tagline': 'You Know, for Search'}
>>>
```

**Comment by sethmlarson** [comment]
Hey all! I'm going to be doing an overhaul of the `elasticsearch-async` package to add async/await (instead of using `yield from`) while updating the API to 7.x. That's a big chunk of work so won't be coming "soon" but is something that's on the radar.

**Comment by sethmlarson** [comment]
`asyncio.run()` is supported by [`elasticsearch[async]`](https://elasticsearch-py.readthedocs.io/en/master/async.html) without requiring the client to be defined inside the event loop.
