### ISSUE TITLE
Why schedule Task instead of just returning Future?

### ISSUE THREAD

**Issue by boc0** [elastic/elasticsearch-py-async#66]
First, thanks for making this.

Trying to await an indexing operation transport.py ensure_future()s the request so it's attached to its own loop. So the task cannot be started in my loop. Why not just return the future without ensure/create_task-ing it?

**Comment by sethmlarson** [comment]
I believe the original intention was so that cancellation was easier? Not sure. Either way this won't be changing as we won't be implementing any breaking changes. See https://github.com/elastic/elasticsearch-py-async/issues/81 for more information.
