### ISSUE TITLE
Elasticsearch 7.x support

### ISSUE THREAD

**Issue by ipeluffo** [elastic/elasticsearch-py-async#67]
Is there any plan to release a version of this library to support Elasticsearch 7.x?

Thanks

**Comment by ipeluffo** [comment]
Any news on this?

**Comment by vEpiphyte** [comment]
@ipeluffo i find installing this package will install the elasticsearch 7.x package since the current constraints do not prohibit elasticsearch 7.x from being installed. Do you not see that package being installed for you?

**Comment by ipeluffo** [comment]
> @ipeluffo i find installing this package will install the elasticsearch 7.x package since the current constraints do not prohibit elasticsearch 7.x from being installed. Do you not see that package being installed for you?

I see that `elasticsearch` 7.x is installed, however I believe this wouldn't be the expected behaviour since `elasticsearch-async` version should match the `elasticsearch` one. For this reason, I needed to pin the `elasticsearch` to 6.x.

**Comment by vEpiphyte** [comment]
@ipeluffo if you try installing elasticsearch<7.0.0 before the async package, pip should see the async package requirements are met.  I do agree though, having proper releases would be good though.

**Comment by sethmlarson** [comment]
Elasticsearch 7 is supported by the `elasticsearch` package by installing the `[async]` extra via `python -m pip install elasticsearch[async]`. [See the documentation for more information](https://elasticsearch-py.readthedocs.io/en/master/async.html).
