### ISSUE TITLE
Drop Python 3.4 support

### ISSUE THREAD

**Issue by vEpiphyte** [elastic/elasticsearch-py-async#70]
Can we drop Python 3.4 support from this library?  It has reached end-of-life and is no longer maintained by the Python Software Foundation. See https://www.python.org/dev/peps/pep-0429/#release-schedule for the 3.4 EOL notice.

Dropping 3.4 would allow us to migrate everything into a modern `async def` syntax and use async generators.  Async generators would allows this library to support scroll/scan API as well as Bulk api's easier.  I've got a fork which implements most of those helpers as async versions already; and it was trivial to do with async generator support.

@HonzaKral @fxdgear

**Comment by vEpiphyte** [comment]
Example bulk helpers and scan support can be seen here
https://github.com/elastic/elasticsearch-py-async/compare/master...vertexproject:feature_bulk_helpers

**Comment by vEpiphyte** [comment]
Upon reading #5 it would probably also be best for us to drop 3.5 as well since then we'll get the proper async generator support (I had previously misread the Python release notes when I put together the original post).

**Comment by sethmlarson** [comment]
Since there will be no further major versions of this package we will not be dropping Python support. Closing this issue.
