### ISSUE TITLE
How to pass querystring params to search?

### ISSUE THREAD

**Issue by arnaudsj** [elastic/elasticsearch-py-async#71]
Hi,

I am trying to pass the following parameter to some of my queries (during tests, to ensure consistency of scoring): ?search_type=dfs_query_then_fetch (as instructed in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-search-type)

What's the best way to pass this along to the search method? I see params in there, but according to a section of the code in transport.py (https://github.com/elastic/elasticsearch-py-async/blob/master/elasticsearch_async/transport.py#L187-L197), it is not clear whether or not the content of params gets serialized in the querystring part for the url request, when a body is present.

Thank you in advance for any pointers!

**Comment by sethmlarson** [comment]
You should be able to pass query parameters the same way you do with the non-async client. Closing this unless there's more to be fixed.
