### ISSUE TITLE
Does this project follow semantic versioning?

### ISSUE THREAD

**Issue by alvassin** [elastic/elasticsearch-py-async#76]
Can i use this project with `~=` operator?
 
```
elasticsearch-async~=6.2.0
```

Does it follow [Semantic versioning](https://semver.org)?

**Comment by sethmlarson** [comment]
This project follows the Elasticsearch major and minor which do follow semantic versioning. Breaking changes will only be introduced on new majors. You should probably use `~=6` if your Elasticsearch cluster is `v6`

Does that answer your question?

**Comment by alvassin** [comment]
Yes, thank you.
