### ISSUE TITLE
ServerDisconnectedError

### ISSUE THREAD

**Issue by paulnovacovici** [elastic/elasticsearch-py-async#77]
When trying to save many documents to an index I'm running into the occasional disconnect for some reason:

`elasticsearch.exceptions.ConnectionError: ConnectionError() caused by: ServerDisconnectedError()`

Any way we to remedy this? Not sure why it happens, but setting up a retry on error may help mitigate this error.

**Comment by sethmlarson** [comment]
aiohttp raises this exception when the server half-closes their end of the socket. I wonder if this is something that is happening when the server closes a keep-alive connection after it's lifetime timeout.

**Comment by sethmlarson** [comment]
Closing this due to lack of information.
