### ISSUE TITLE
Is this repository maintained by elastic at all?

### ISSUE THREAD

**Issue by shadiramadan** [elastic/elasticsearch-py-async#78]
Has elastic abandoned this repository?

There are a bunch of MRs up with no replies what so ever for over a year.

You can't expect anyone to make an effort to contribute if they can't even expect anything to be upstreamed.

**Comment by sethmlarson** [comment]
We're working towards adding proper async support to the `elasticsearch` package rather than packaging them seperately.

See: https://github.com/elastic/elasticsearch-py/pull/1203

**Comment by shadiramadan** [comment]
Thanks for directing me to that @sethmlarson !  That's a recent PR too!  Very excited to see that.
