### ISSUE TITLE
Add a note or constraint for elasticsearch 5 compatibility

### ISSUE THREAD

**Issue by mjrk** [elastic/elasticsearch-py-async#8]
This library can partially be used with elasticsearch-py >= 5.0.0, but it breaks during error handling. There are different method signatures for log_request_fail

elasticsearch_async/connection.py:

    self.log_request_fail(method, url, body, self.loop.time() - start, exception=e)

versus /elasticsearch/connection/base.py:

    log_request_fail(self, method, full_url, path, body, duration, status_code=None, response=None, exception=None):

Note the newly added 'path' argument.

You may want to update the setup.py (elasticsearch <= 5.0.0) or leave a note.

Btw. this library is great work!

**Comment by stickperson** [comment]
I think this is a problem with _all_ versions of elasticsearch-py. I was about to submit a PR to fix this but then I saw this issue.

Every call to `self.log_request_path` is missing the `url_path`. My PR fixes that. Let me know if I should submit it.

**Comment by mjrk** [comment]
I see. Cool and thanks for your efforts!
