### ISSUE TITLE
ANNOUNCE: Asyncio is now supported natively in the 'Elasticsearch' package

### ISSUE THREAD

**Issue by sethmlarson** [elastic/elasticsearch-py-async#81]
Starting in version 7.8.0 of the [`elasticsearch`](https://pypi.org/project/elasticsearch) package [Asyncio is now supported natively with `async`/`await` on Python 3.6+](https://elasticsearch-py.readthedocs.io/en/master/async.html).
Due to this, this library is now deprecated and will not be adding new features or receiving updates beyond impactful bug fixes for Elasticsearch 6.x.

You can install async support via:

```bash
$ python -m pip install elasticsearch[async]
```

**NOTE: If you're still targetting Elasticsearch 6.x you should continue to use this library until you've upgraded to Elasticsearch 7.x or later**

- GitHub Project: https://github.com/elastic/elasticsearch-py
- Documentation: https://elasticsearch-py.readthedocs.io
- Issue Tracker: https://github.com/elastic/elasticsearch-py/issues

**Comment by aockel** [comment]
(@sethmlarson: migrated this issue to https://github.com/elastic/elasticsearch-py/issues/1333)

**Comment by sethmlarson** [comment]
@aockel This isn't the appropriate place to raise this issue, I'm going to migrate it to the main repository and tag you.
